apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    # Optional: Enable path rewriting if you want to strip the prefix
    # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /my-app
            pathType: Prefix
            backend:
              service:
                name: {{ include "nodejs-app.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
          - path: /metrics
            pathType: Exact
            backend:
              service:
                name: {{ include "nodejs-app.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
          - path: /ready
            pathType: Exact
            backend:
              service:
                name: {{ include "nodejs-app.fullname" . }}
                port:
                  number: {{ .Values.service.port }}