apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nodejs-app.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    # For later use for SSL with cert-manager:
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
    - http:
        paths:
          - path: /my-app
            pathType: Prefix
            backend:
              service:
                name: {{ include "nodejs-app.fullname" . }}
                port:
                  number: {{ .Values.service.port }}