replicaCount: 2

image:
  repository: 704505749045.dkr.ecr.us-east-1.amazonaws.com/liorm-nodejs-app
  tag: "1.0.0-build-5"
  pullPolicy: IfNotPresent

labels:
  app: nodejs-app
  service: nodejs-app

service:
  type: LoadBalancer
  port: 80
  containerPort: 8080

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi